name: Backup FirebaseRealtimeDatabase Counts

on:
  schedule:
    # 日本時間(UTC+9) 22時
    - cron: "0 13 * * *"
  workflow_dispatch:

jobs:
  backup-counts:
    name: FirebaseRealtimeDatabaseのバックアップを取得する
    environment: Backup FirebaseRealtimeDatabase Counts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_PAT || github.token }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: counts を更新する
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          npm install && node ./node_modules/.bin/firebase database:get -o counts.json /counts && echo "$(date '+%F'),$(jq '[.[] | .count] | add' counts.json)" >> dataset/firebase/counts.csv
      - name: Diff
        id: diff
        run: |
          git add -N dataset/firebase
          git diff --name-only --exit-code
        continue-on-error: true
      - name: Commit & Push
        run: |
          set -x
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add dataset/firebase
          git commit --author=. -m '[skip ci] update counts'
          git push
        if: steps.diff.outcome == 'failure'
