name: Update video list

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  update-video-list:
    name: チャンネルの動画一覧を取得し更新する
    environment: Update Video List
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_PAT || github.token }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
      - name: チャンネルの動画一覧を取得
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: |
          ./scripts/get_youtube_channel_video_list/main.sh
          ruby scripts/search_list_to_yaml/update_videolist_json.rb
      - name: Diff
        id: diff
        run: |
          git add -N .
          git diff --name-only --exit-code
        continue-on-error: true
      - name: Commit & Push
        run: |
          set -x
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit --author=. -m '[skip ci] update video list'
          git push
        if: steps.diff.outcome == 'failure'
      - name: Deploy to GitHub Pages
        uses: .github/workflows/deploy-page.yml
        if: steps.diff.outcome == 'failure'
